apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multus-access-binding
subjects:
  - kind: ServiceAccount
    name: default  # or the specific service account your pods are using
    namespace: multus-service-demo
roleRef:
  kind: ClusterRole
  name: multus-access
  apiGroup: rbac.authorization.k8s.io
