apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multus-access
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "endpointslices"]
    verbs: ["get", "list", "watch"]
